version: '3'

services:
  mariadb:
    container_name: mariadb_soapp
    image: bitnami/mariadb:10.7.8-debian-11-r6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_USER=${DB_USERNAME}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3310:3306
    volumes:
      - soapp_volume:/bitnami/mariadb
  bitnami:
    container_name: bitnami_soapp
    image: bitnami/laravel:7.0.0-debian-10-r7
    working_dir: /app
    volumes:
      #- /home/david/Software/soapp_laravel:/app
      - /mnt/c/software/soapp_laravel:/app
    ports:
      #- "0.0.0.0:8080:8000" 
      #- ":::8010:8000"
      - 8010:8000
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}     
    command: >
      sh -c "composer install && npm run start"    
    depends_on:
      - mariadb     

  phpmyadmin:
    container_name: phpmyadmin_soapp
    image: bitnami/phpmyadmin:5.2.1-debian-12-r33
    ports:
      - '8081:8080'
      - '443:8443'
    depends_on:
      - mariadb
      
volumes:
  soapp_volume:
    external: true